name: tests

on: 
  push:
      branches:
          - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    env:
        opoverridever: 0.1.0
        testlib: 0.0.10
        opoverriderep: ${{ github.repository_owner }}/rindow-opoverride
        owner: ${{ github.repository_owner }}

    strategy:
        fail-fast: true
        matrix:
          include:
            - name: PHP8.1
              os: ubuntu-22.04
              php: '8.1'
              phpunit: '10.5'
            - name: PHP8.4
              os: ubuntu-latest
              php: '8.4'
              phpunit: '11.5'
            - name: Windows
              os: windows-latest
              arch: 'x64'
              php: '8.4'
              phpunit: '11.5'
            #- name: macOS
            #  os: macos-latest
            #  arch: 'arm64'
            #  php: '8.4'
            #  phpunit: '11.5'
            #  ffi: 'ffi'
    

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer, phpstan
          ini-values: "memory_limit=512M"
          extensions: mbstring
        env:
          fail-fast: true

      - name: Install PHP Extension (Linux)
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          wget https://github.com/${{ env.opoverriderep }}/releases/download/${{ env.testlib }}/rindow-opoverride-php${{ matrix.php }}_${{ env.opoverridever }}_amd64.deb
          sudo apt install -y ./rindow-opoverride-php${{ matrix.php }}_${{ env.opoverridever }}_amd64.deb

      - name: Install PHP Extension (Windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          Invoke-WebRequest -Uri https://github.com/${{ env.opoverriderep }}/releases/download/${{ env.testlib }}/rindow_opoverride-php${{ matrix.php }}-${{ env.opoverridever }}-win-nts-vs17-x64.zip -OutFile rindow_opoverride.zip
          Expand-Archive -Path rindow_opoverride.zip
          Remove-Item rindow_opoverride.zip
          copy php_rindow_opoverride.dll C:\tools\php\ext\.
          echo "" >> C:\tools\php\php.ini
          echo "extention=rindow_opoverride" >> C:\tools\php\php.ini

      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Composer
        run: |
          composer update
          composer require --dev phpunit/phpunit=^${{ matrix.phpunit }}

      - name: PHP Static Analysys
        run: phpstan

      - name: PHPUnit Tests
        run: vendor/bin/phpunit -c tests
